version: '3.5.11'
services:
  mysql:
    image: mysql:8.0
    container_name: tienda_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tienda_bicicletas
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tienda_net

  app:
    build: .  # Construye la imagen usando el Dockerfile
    container_name: tienda_backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tienda_bicicletas?useSSL=false
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
    ports:
      - "8080:8080"
    networks:
      - tienda_net

volumes:
  mysql_data:

networks:
  tienda_net: