spring.application.name=tienda-bicicletas

spring.datasource.url=jdbc:mysql://localhost:3308/tienda_bicicletas?useSSL=false&serverTimezone=UTC
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never

server.port=8080